export const APP_ROUTE = {
  unRegistered: '*',
  browserBase: '/',
  appBase: '/*',
  notFound: '/not-found',
  signIn: '/sign-in',
  signUp: '/sign-up',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password/:resetJWT',
  dashboard: '/dashboard',
  requests: '/requests',
  serialNumbers: '/serial-numbers',
  certificates: '/certificates',
  customers: '/customers',
  employees: '/employees',
  dealers: '/dealers',
  addDealer: '/dealers/add-dealer',
  dealerDetails: '/dealers/:dealerId',
  analytics: '/analytics',
};
